# -*- coding: utf-8 -*-
"""Plot_occurrence_rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkFs7Nf_hgUpbLx3LufwFi706B_HWhX9
"""

import pandas as pd
import argparse

def consolidate_excel_sheets(input_filename, output_filename):
    # Load the input Excel file
    xls = pd.ExcelFile(input_filename)

    # Specify the age groups to read and consolidate
    age_groups = [3, 6, 9, 12, 18, 24, 30]

    # Initialize an empty list to store DataFrames
    consolidated_data = []

    # Loop through each age group and read the corresponding sheet
    for age in age_groups:
        sheet_name = f"{age}_Summary"

        # Check if the sheet exists in the file to avoid errors
        if sheet_name in xls.sheet_names:
            df = pd.read_excel(xls, sheet_name=sheet_name)
            df['Age_Group'] = age  # Add an Age_Group column for identification
            # Reorder columns to make 'Age_Group' the first column
            cols = ['Age_Group'] + [col for col in df.columns if col != 'Age_Group']
            df = df[cols]
            consolidated_data.append(df)
        else:
            print(f"Sheet {sheet_name} not found in the input file.")

    # Concatenate all DataFrames
    if consolidated_data:
        consolidated_df = pd.concat(consolidated_data, ignore_index=True)

        # Write the consolidated DataFrame to an output Excel file
        with pd.ExcelWriter(output_filename) as writer:
            consolidated_df.to_excel(writer, index=False, sheet_name='Consolidated_Summary')

        print(f"Consolidated data written to {output_filename}")
    else:
        print("No data found to consolidate.")

if __name__ == "__main__":
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description="Consolidate specific sheets from an input Excel file into a single output file.")
    parser.add_argument("input_file", help="Path to the input Excel file")
    args = parser.parse_args()
    output_filename = './consolidated_MCDI_word_counts_for_age_groups.xlsx'

    # Run the consolidation function with command-line arguments
    consolidate_excel_sheets(args.input_file, output_filename)

